input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/lr_model.pkl"
metric_report_path: "output/lr_metrics.json"
splitting_params:
  split_size: 0.2
  random_state: 42
  shuffle: True
train_params:
  model: "LogisticRegression"
  model_params:
    C: 1.0
    fit_intercept: True
    random_state: 42
    solver: "liblinear"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"
  categorical_transformation: "OneHotEncoder"
  numerical_transformation: "StandardScaler"