input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/rf_model.pkl"
metric_report_path: "output/rf_metrics.json"
splitting_params:
  split_size: 0.2
  random_state: 42
  shuffle: True
train_params:
  model: "RandomForestClassifier"
  model_params:
    n_estimators: 600
    max_depth: 6
    random_state: 42
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"
  categorical_transformation: "OneHotEncoder"
  numerical_transformation: ''